---
- name: install vsftpd
  package:
    name:
     - vsftpd
    state: latest
- name: install semanage
  package:
    name: 
     - python3-libsemanage
     - policycoreutils-python-utils

- name: creating upload directory
  file:
    path: "{{ anon_root }}"
    state: directory
    mode: '0777'

- name: creating pub directory
  file:
    path: "{{ local_root }}"
    state: directory
    mode: '0744'
      
- name: SELinux permissions
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
  notify: restart vsftpd
 
- name: copy config file
  template:
    src: vsftpd_conf.j2
    dest: "{{ vsftpd_path }}"
    mode: '0600'
  notify: restart vsftpd

- name: starting vsftpd
  service: 
    name: vsftpd
    enabled: true
    state: started
...