---
- name: install vsftpd
  package:
    name:
     - vsftpd
    state: latest
- name: install semanage
  package:
    name: 
     - python3-libsemanage
     - policycoreutils-python-utils

- name: creating anon directory
  file:
    path: "{{ anon_root }}"
    state: directory

- name: creating upload directory
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: '0777'
    
- name: SELinux permissions
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
  notify: restart vsftpd
 
- name: One more SELinux permission
   sefcontext:
      target: '/var/ftp/pub/upload(/.*)?' 
      setype: public_content_rw_t
      state: present      
 
- name: copy config file
  template:
    src: vsftpd_conf.j2
    dest: "{{ vsftpd_path }}"
    mode: '0600'
  notify: restart vsftpd

- name: starting vsftpd
  service: 
    name: vsftpd
    enabled: true
    state: started
    
- name: Run restore context to reload selinux
  command: restorecon -irv /var/ftp/pub/upload
...