---
- name: install apache
  package:
    name:
     - httpd
    state: latest
- name: starting apache
  service: name=httpd state=started
 
- name: copy start page
  template:
    src: templates/page.j2
    dest: /var/www/html/index.html
  notify:
    - apache restart
    
- name: give port access
  firewalld:
    port: "{{ port_to_open }}"
    permanent: yes
    state: enabled
...